apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuario-app
  namespace: hackathon-fiap
  labels:
    app.kubernetes.io/name: usuario-app
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: usuario-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: usuario-app
    spec:
      serviceAccountName: usuario-serviceaccount
      containers:
        - name: usuario-app
          image: DOCKER_IMAGE
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "256m"
              memory: "512M"
            limits:
              cpu: "512m"
              memory: "2048M"
          env:
            - name: COGNITO_URL
              valueFrom:
                configMapKeyRef:
                  name: usuario-configmap
                  key: cognito_url
            - name: COGNITO_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: usuario-configmap
                  key: cognito_client_id
            - name: COGNITO_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: usuario-configmap
                  key: cognito_client-secret
            - name: COGNITO_USER_POOL_ID
              valueFrom:
                configMapKeyRef:
                  name: usuario-configmap
                  key: cognito_user_pool_id
            - name: AWS_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: usuario-configmap
                  key: aws_secret_key
            - name: AWS_SESSION_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: usuario-configmap
                  key: aws_session_token
            - name: AWS_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: usuario-configmap
                  key: aws_access_key
          ports:
            - name: http-port
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http-port
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http-port
            initialDelaySeconds: 240
            periodSeconds: 15
            failureThreshold: 3