apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuario-app
  namespace: hackathon-fiap
  labels:
    app.kubernetes.io/name: usuario-app
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: usuario-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: usuario-app
    spec:
      serviceAccountName: usuario-serviceaccount
      containers:
        - name: usuario-app
          image: DOCKER_IMAGE
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "256m"
              memory: "512M"
            limits:
              cpu: "512m"
              memory: "2048M"
          env:
            - name: S3_URL
              valueFrom:
                configMapKeyRef:
                  name: usuario-configmap
                  key: s3_url
            - name: SNS_URL
              valueFrom:
                configMapKeyRef:
                  name: usuario-configmap
                  key: sns_url
            - name: SNS_ARN
              valueFrom:
                configMapKeyRef:
                  name: usuario-configmap
                  key: novo_video_recebido_sns
            - name: AWS_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: usuario-configmap
                  key: aws_secret_key
            - name: AWS_SESSION_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: usuario-configmap
                  key: aws_session_token
            - name: AWS_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: usuario-configmap
                  key: aws_access_key
            - name: ENVIOS_URL
              valueFrom:
                configMapKeyRef:
                  name: usuario-configmap
                  key: envios_url
          ports:
            - name: http-port
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http-port
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http-port
            initialDelaySeconds: 240
            periodSeconds: 15
            failureThreshold: 3